name: 'Setup Qiita CLI'
description: 'Sets up Qiita CLI in your GitHub Actions workflow.'

inputs:
  version:
    required: false
    description: 'The version of Qiita CLI to install.'
    default: 'latest'
  github-token:
    required: false
    description: 'Used to pull Qiita CLI from Github'
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'
