name: update dist

on:
  workflow_dispatch:

jobs:
  update-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: yarn
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build
      - name: git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: commit dist
        run: |
          git add dist
          if git diff --staged --quiet --exit-code; then
            echo "There is no changes."
          else
            git commit -m "update dist"
            git push origin main
          fi
