name: update dist

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: yarn
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build
      - name: git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: commit dist
        run: |
          git add dist
          if git diff --staged --quiet --exit-code; then
            echo "There is no changes."
          else
            git commit -m "update dist"
            git push origin main
          fi

  ci:
    needs: [update-dist]
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
        os:
          # windows
          - windows-latest
          - windows-2022
          - windows-2019
          # ubuntu
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04
          # macos
          - macos-latest
          - macos-12
          - macos-11
          - macos-10.15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: koki-develop/setup-qiita-cli@main
        with:
          version: latest
          access-token: ${{ secrets.QIITA_ACCESS_TOKEN }}
      - run: qiita --version
